### ISSUE TITLE
Error from HelloWorld Example

### ISSUE THREAD

**Issue by jayakusumah** [aws/aws-greengrass-core-sdk-js#8]
I followed step by step (Getting Started - Hello World) , and got an error

```
{
  "errorType": "TypeError",
  "errorMessage": "ggSdk.IotData is not a constructor",
  "trace": [
    "TypeError: ggSdk.IotData is not a constructor",
    "    at Object.<anonymous> (/var/task/index.js:16:19)",
    "    at Module._compile (internal/modules/cjs/loader.js:955:30)",
    "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)",
    "    at Module.load (internal/modules/cjs/loader.js:811:32)",
    "    at Function.Module._load (internal/modules/cjs/loader.js:723:14)",
    "    at Module.require (internal/modules/cjs/loader.js:848:19)",
    "    at require (internal/modules/cjs/helpers.js:74:18)",
    "    at _tryRequire (/var/runtime/UserFunction.js:75:12)",
    "    at _loadUserApp (/var/runtime/UserFunction.js:95:12)",
    "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)"
  ]
}
```

and 

```
oader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/aws-greengrass-core-sdk/lambda.js',
    '/var/task/node_modules/aws-greengrass-core-sdk/index.js',
    '/var/task/index.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2020-03-13T17:31:19.105Z	undefined	ERROR	Unable to load aws-greengrass-core-sdk.IotData due to:  Error: Cannot find module 'aws-greengrass-common-js'
Require stack:
- /var/task/node_modules/aws-greengrass-core-sdk/iotdata.js
- /var/task/node_modules/aws-greengrass-core-sdk/index.js
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/task/node_modules/aws-greengrass-core-sdk/iotdata.js:7:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/aws-greengrass-core-sdk/iotdata.js',
    '/var/task/node_modules/aws-greengrass-core-sdk/index.js',
    '/var/task/index.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2020-03-13T17:31:19.162Z	undefined	ERROR	Unable to load aws-greengrass-core-sdk.SecretsManager due to:  Error: Cannot find module 'aws-greengrass-common-js'
Require stack:
- /var/task/node_modules/aws-greengrass-core-sdk/secretsmanager.js
- /var/task/node_modules/aws-greengrass-core-sdk/index.js
- /var/task/index.js
- /var/runtime/UserFunction.js
- /var/runtime/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/var/task/node_modules/aws-greengrass-core-sdk/secretsmanager.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/var/task/node_modules/aws-greengrass-core-sdk/secretsmanager.js',
    '/var/task/node_modules/aws-greengrass-core-sdk/index.js',
    '/var/task/index.js',
    '/var/runtime/UserFunction.js',
    '/var/runtime/index.js'
  ]
}
2020-03-13T17:31:19.483Z	undefined	ERROR	Uncaught Exception 	{"errorType":"TypeError","errorMessage":"ggSdk.IotData is not a constructor","stack":["TypeError: ggSdk.IotData is not a constructor","    at Object.<anonymous> (/var/task/index.js:16:19)","    at Module._compile (internal/modules/cjs/loader.js:955:30)","    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)","    at Module.load (internal/modules/cjs/loader.js:811:32)","    at Function.Module._load (internal/modules/cjs/loader.js:723:14)","    at Module.require (internal/modules/cjs/loader.js:848:19)","    at require (internal/modules/cjs/helpers.js:74:18)","    at _tryRequire (/var/runtime/UserFunction.js:75:12)","    at _loadUserApp (/var/runtime/UserFunction.js:95:12)","    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)"]}
END RequestId: 3577f159-cea9-41c1-9dea-50f647357afe
REPORT RequestId: 3577f159-cea9-41c1-9dea-50f647357afe	Duration: 1879.64 ms	Billed Duration: 1900 ms	Memory Size: 128 MB	Max Memory Used: 22 MB	
Unknown application error occurred
TypeError
```

**Comment by MikeDombo** [comment]
This SDK can only be used when run on Greengrass. It does not work when running on the cloud lambda. If you deploy your function onto your Greengrass device, then it should work for you.

**Comment by ambarus** [comment]
Hi, Mike. How can I deploy the function on my Greengrass device? Is there a tutorial that I can follow? Cheers.
